### ISSUE TITLE
Create Jenkins jobs for testing and/or autoreleasing Debian packages

### ISSUE THREAD

**Issue by axch** [probcomp/packaging#1]
From Flowdock:

 Riastradh

```
(
    wget http://probcomp.csail.mit.edu/ubuntu/code-signer.key
    diff -u <(echo '892e90c783472714e9089f3c0658936eb07a9c5250b4e2d2b5b9c82d300c5f48  code-signer.key') \
        <(sha256sum code-signer.key) \
    || exit 1
    sudo apt-key add code-signer.key
    sudo apt-add-repository -s http://probcomp.csail.mit.edu/ubuntu
    sudo apt-get update
    sudo apt-get install bayeslite venture
)
```

(An existing installation in /usr/local from `pip install .` or something may override what you install with apt.)
@team, This Ubuntu package repository is not published anywhere, unless there is a way to get a directory listing from http://probcomp.csail.mit.edu/, so we have time to nuke it and start over, but it should be good to go for anyone to use at the summer school tomorrow.
@team, I can push out updates pretty easily -- I'm using reprepro and rsync right now.  (Updates won't be atomic, but since this is a low-volume repository, that's not a big issue.)  The scripts that build packages and publish them in the correct repository format using reprepro are in the Github `debian' repository.  The master is on my laptop -- I'm just rsyncing it to afs for now.  Very little of how to do this is not in Git, just a single trivial configuration file for reprepro.
@team, All that said: before telling anyone to try using it tomorrow, let's make sure it works for someone other than me first.
20:17
Next week perhaps Someone^TM should hook this up to jenkins or something.

**Comment by gregory-marton** [comment]
Officially not supporting Debian with packages per se. Have added a bayeslite Docker test over ubuntu, have a bdbcontrib one almost ready, and will add more.
