### ISSUE TITLE
pip install [...] no such option: --no-cache-dir

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/packaging#10]
pip version in the installed virtual environment (at probcomp) is outdated. This might be the case with other users too.

Solution: add `pip install pip --upgrade` after activating the venv.

**Comment by DannyDannyDanny** [comment]
I still get the error after upgrading

```
Python 3.7 
Pip 19.2.3
```

Running: `pip install -v --no-chache-dir ./`
Gives following output:
```
Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --no-chache-dir
```

I'm following [this notebook](https://colab.research.google.com/drive/1mR5DcND9JCxqr1rXsavVYKzFQq4gOI5-?usp=drive_open#scrollTo=t467k4q5moml)

**Comment by rcgale** [comment]
"chache"

**Comment by DannyDannyDanny** [comment]
embarrassing

**Comment by vivekrk2** [comment]
pip cache purge

then try pip install
