### ISSUE TITLE
Script for installing bayeslite on fresh Ubuntu LTS including system-wide installs

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/packaging#13]
Such as pip and virtualenv. I'm currently doing some tests in a VM and will soon post the errors I've encountered, as well as possible solutions.

**Comment by gregory-marton** [comment]
Exists in packaging/bayeslite/LTS-Dockerfile

Gregory Marton
617-858-0775
http://csail.mit.edu/~gremio/cal
