### ISSUE TITLE
curl not present in mitprobcomp/bayeslite-notebook docker image

### ISSUE THREAD

**Issue by alxempirical** [probcomp/packaging#17]
This leads to the first cell failing in `Satellites.ipynb`.

**Comment by gregory-marton** [comment]
d'oh! I should have run that test...

On Thu, May 26, 2016 at 4:44 PM, Alex Coventry notifications@github.com
wrote:

> This leads to the first cell failing in Satellites.ipynb.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/probcomp/packaging/issues/17

## 

## Gregory Marton

gremio@mit.edu
617-858-0775
http://csail.mit.edu/~gremio/cal
