### ISSUE TITLE
osx dmg doesn't import baselite

### ISSUE THREAD

**Issue by tibbetts** [probcomp/packaging#7]
On current 0.1.3rc2
sys.path doesn't point into /Application when running in the webnotebook.
It does point there when running ipython command line
It does not point there when running command line regular python.

**Comment by riastradh-probcomp** [comment]
Can you please specify exactly how you are invoking Python to determine sys.path?  That is -- double-clicking .app and printing in the ipython notebook? running ipython from a shell? or running python from a shell?  If from a shell, can you show a transcript of exactly what you ran, starting with running `env` and `pwd` and then the Python incantation?

**Comment by tibbetts** [comment]
Works in latest build.
