### ISSUE TITLE
Stuck on ipython==3.2.1

### ISSUE THREAD

**Issue by gregory-marton** [probcomp/packaging#8]
First issue I ran into in upgrading: ipython 4.0 requires notebooks to be signed. As far as I can tell, this just means that the demo must

```
ipython trust Satellites.ipynb
```

before actually launching it. I'm not sure how that's helpful, but I'm happy to comply. Unsure if there's anything else.

**Comment by riastradh-probcomp** [comment]
I would guess there's some way for someone distributing notebooks to sign them and publish their key, for time-of-first-use verification -- the only chance a forger has to maliciously distribute notebooks is when the user first loads the key, like with ssh host keys, and after that the forger can't persuade the user to use any notebook which the user's software expects to be signed by the same key.
